# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xafsdbpy
from xafsdbpy.api.item_api import ItemApi  # noqa: E501
from xafsdbpy.rest import ApiException


class TestItemApi(unittest.TestCase):
    """ItemApi unit test stubs"""

    def setUp(self):
        self.api = xafsdbpy.api.item_api.ItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_item_list_get(self):
        """Test case for api_v1_item_list_get

        Api List Items  # noqa: E501
        """
        pass

    def test_api_v1_item_upload_post(self):
        """Test case for api_v1_item_upload_post

        Api Upload Item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
