# Dockerfile

FROM python:3.7.6-buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    unixodbc-dev \
    unixodbc \
    libpq-dev
RUN apt-get install dos2unix
RUN apt-get -y install python3-dev

RUN mkdir -p /opt/app
RUN mkdir -p /opt/app/pip_cache

WORKDIR /opt/app

#COPY webserver /opt/app

#COPY xafsdb_web /opt/app

#COPY manage.py /opt/app

#COPY auto_dataset_create.py /opt/app

#COPY db.sqlite3 /opt/app

COPY scicat_py /opt/app
RUN pip install -e /opt/app

#COPY requirements.txt /app/
#TODO: xafsdb_1 | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment
#RUN pip install -r requirements.txt

COPY requirements_create.txt /opt/app/requirements_create.txt

RUN pip install -r /opt/app/requirements_create.txt --cache-dir /opt/app/pip_cache --ignore-installed

COPY . /opt/app
RUN ls ./

RUN /usr/local/bin/python -m pip install --upgrade pip

#EXPOSE 8000

CMD ["python","/opt/app/auto_dataset_create.py"]

#RUN ls -la /opt/app/*
#RUN cd "/opt/app/quality_control/example data/LABORATORY" && ls -la