# coding: utf-8

"""
    Dacat API

    SciCat backend API  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import datetime
import unittest

import scicat_py
from scicat_py.models.update_proposal_dto import UpdateProposalDto  # noqa: E501
from scicat_py.rest import ApiException


class TestUpdateProposalDto(unittest.TestCase):
    """UpdateProposalDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateProposalDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = scicat_py.models.update_proposal_dto.UpdateProposalDto()  # noqa: E501
        if include_optional:
            return UpdateProposalDto(
                owner_group="0",
                access_groups=["0"],
                created_by="0",
                updated_by="0",
                proposal_id="0",
                pi_email="0",
                pi_firstname="0",
                pi_lastname="0",
                email="0",
                firstname="0",
                lastname="0",
                title="0",
                abstract="0",
                start_time=datetime.datetime.strptime(
                    "2013-10-20 19:20:30.00", "%Y-%m-%d %H:%M:%S.%f"
                ),
                end_time=datetime.datetime.strptime(
                    "2013-10-20 19:20:30.00", "%Y-%m-%d %H:%M:%S.%f"
                ),
            )
        else:
            return UpdateProposalDto()

    def testUpdateProposalDto(self):
        """Test UpdateProposalDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
