# coding: utf-8

"""
    Dacat API

    SciCat backend API  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import scicat_py
from scicat_py.api.published_data_api import PublishedDataApi  # noqa: E501
from scicat_py.rest import ApiException


class TestPublishedDataApi(unittest.TestCase):
    """PublishedDataApi unit test stubs"""

    def setUp(self):
        self.api = scicat_py.api.published_data_api.PublishedDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_published_data_controller_count(self):
        """Test case for published_data_controller_count"""
        pass

    def test_published_data_controller_create(self):
        """Test case for published_data_controller_create"""
        pass

    def test_published_data_controller_find_all(self):
        """Test case for published_data_controller_find_all"""
        pass

    def test_published_data_controller_find_one(self):
        """Test case for published_data_controller_find_one"""
        pass

    def test_published_data_controller_form_populate(self):
        """Test case for published_data_controller_form_populate"""
        pass

    def test_published_data_controller_register(self):
        """Test case for published_data_controller_register"""
        pass

    def test_published_data_controller_remove(self):
        """Test case for published_data_controller_remove"""
        pass

    def test_published_data_controller_resync(self):
        """Test case for published_data_controller_resync"""
        pass

    def test_published_data_controller_update(self):
        """Test case for published_data_controller_update"""
        pass


if __name__ == "__main__":
    unittest.main()
