# coding: utf-8

"""
    Dacat API

    SciCat backend API  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import datetime
import unittest

import scicat_py
from scicat_py.models.technique import Technique  # noqa: E501
from scicat_py.rest import ApiException


class TestTechnique(unittest.TestCase):
    """Technique unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Technique
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = scicat_py.models.technique.Technique()  # noqa: E501
        if include_optional:
            return Technique(pid="0", name="0")
        else:
            return Technique(
                pid="0",
                name="0",
            )

    def testTechnique(self):
        """Test Technique"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
