site_name: RefXAS - Reference database for XAS
site_url: https://san-wierpa.github.io/refxas_docs/
repo_url: https://github.com/San-WierPa/xafsdb_webserver

copyright: Copyright &copy; 2022 - 2024 Sebastian Paripsa

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/San-WierPa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sebastian-paripsa/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<paripsa@uni-wuppertal.de>

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - attr_list
  - md_in_html